export const COMMON_TEXTS = {
  // Generic buttons
  BUTTONS: {
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    ADD: "Add",
    REMOVE: "Remove",
    SUBMIT: "Submit",
    RESET: "Reset",
    CLOSE: "Close",
    CONFIRM: "Confirm",
    YES: "Yes",
    NO: "No",
    OK: "OK",
    APPLY: "Apply",
    CLEAR: "Clear",
    REFRESH: "Refresh",
    RELOAD: "Reload",
    RETRY: "Retry",
    CONTINUE: "Continue",
    BACK: "Back",
    NEXT: "Next",
    PREVIOUS: "Previous",
    FINISH: "Finish",
    DONE: "Done",
  },

  // Generic labels
  LABELS: {
    NAME: "Name",
    EMAIL: "Email",
    PASSWORD: "Password",
    PHONE: "Phone",
    ADDRESS: "Address",
    DATE: "Date",
    TIME: "Time",
    STATUS: "Status",
    TYPE: "Type",
    CATEGORY: "Category",
    DESCRIPTION: "Description",
    TITLE: "Title",
    ROLE: "Role",
    PERMISSIONS: "Permissions",
  },

  // Generic status
  STATUS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    DRAFT: "Draft",
    PUBLISHED: "Published",
    ARCHIVED: "Archived",
  },

  // Generic messages
  MESSAGES: {
    NO_DATA: "No data available",
    LOADING: "Loading...",
    SAVING: "Saving...",
    DELETING: "Deleting...",
    PROCESSING: "Processing...",
    SUCCESS: "Success",
    ERROR: "Error",
    WARNING: "Warning",
    INFO: "Information",
  },

  // Generic placeholders
  PLACEHOLDERS: {
    SEARCH: "Search...",
    SELECT: "Select...",
    ENTER_TEXT: "Enter text...",
    CHOOSE_FILE: "Choose file...",
    SELECT_DATE: "Select date...",
    SELECT_TIME: "Select time...",
  },

  // Task-specific texts
  TASK: {
    BUTTONS: {
      CREATE_TASK: "Create Task",
      EDIT_TASK: "Edit Task",
      DELETE_TASK: "Delete Task",
      DUPLICATE_TASK: "Duplicate Task",
      VIEW_TASK: "View Task",
      SAVE_CHANGES: "Save Changes",
      RESET_FORM: "Reset Form",
      CLEAR_FILTERS: "Clear Filters",
      ADD_TAG: "Add Tag",
      REMOVE_TAG: "Remove Tag",
    },
    LABELS: {
      TASK_ID: "Task ID",
      TASK_TITLE: "Task Title",
      TASK_DESCRIPTION: "Task Description",
      TASK_STATUS: "Status",
      TASK_PRIORITY: "Priority",
      TASK_TYPE: "Type",
      DUE_DATE: "Due Date",
      ESTIMATED_HOURS: "Estimated Hours",
      ASSIGNED_TO: "Assigned To",
      CREATED_BY: "Created By",
      CREATED_DATE: "Created Date",
      COMPLETED_DATE: "Completed Date",
      TAGS: "Tags",
    },
    PLACEHOLDERS: {
      SEARCH_TASKS: "Search tasks...",
      ENTER_TITLE: "Enter task title...",
      ENTER_DESCRIPTION: "Enter task description...",
      SELECT_STATUS: "Select status...",
      SELECT_PRIORITY: "Select priority...",
      SELECT_TYPE: "Select type...",
      SELECT_DUE_DATE: "Select due date...",
      ENTER_HOURS: "Enter estimated hours...",
      ADD_TAG: "Add a tag...",
    },
    MESSAGES: {
      NO_TASKS: "No tasks found",
      LOADING_TASKS: "Loading tasks...",
      CREATING_TASK: "Creating task...",
      UPDATING_TASK: "Updating task...",
      DELETING_TASK: "Deleting task...",
      TASK_CREATED: "Task created successfully!",
      TASK_UPDATED: "Task updated successfully!",
      TASK_DELETED: "Task deleted successfully!",
      UNSAVED_CHANGES: "You have unsaved changes. Are you sure you want to leave?",
      DELETE_CONFIRMATION: "Are you sure you want to delete this task? This action cannot be undone.",
    },
  },
} as const
